prettier/vim-prettier

README.md, doc/prettier.txt, plugin/prettier.vim
This fixes issue https://github.com/mitermayer/vim-prettier/issues/9
=> Prettier CLI seems to expect 'false' for some parameters instead of 0

README.md, autoload/prettier.vim, doc/prettier.txt, ftplugin/css.vim, ftplugin/less.vim, ftplugin/scss.vim, ftplugin/typescript.vim, package.json, plugin/prettier.vim
- Adding user configuration to allow running async formatting by default
- Adding support for typescript, css, less, scss formatting
- Bumping prettier plugin
=> Bumping support to latest prettier ^1.4.X and enabling support for

README.md, autoload/prettier.vim, doc/prettier.txt, plugin/prettier.vim
- Adding configuration toggle for controlling error quick fix parsing
- Adding PrettierAsync command
- Fixing configuration bug where boolean values where not correctly parsed
- Making sure that async jobs do not execute if already in progress
=> Adding async command and configuration controls

autoload/prettier.vim
=> adding-support-for-vim7 - adding support for vim7

LICENSE, package.json
Including license file
Fixes: https://github.com/prettier/vim-prettier/issues/33
=> Adding MIT license

package.json
Bumping internal prettier plugin version
Fixes: https://github.com/prettier/vim-prettier/issues/34
=> Bumping prettier internal dependencie plugin to 1.5.3

CHANGELOG.md
- Changelog has been generated using (https://github.com/skywinder/github-changelog-generator)
Fixes: https://github.com/prettier/vim-prettier/issues/35
=> Adding changelog file

README.md
Also fixed typos and did a little Readme cleanup automatically with Remark.
=> Added extensions to vim configuration example

README.md, autoload/prettier.vim, doc/prettier.txt, plugin/prettier.vim
This includes more commands to interact with the prettier CLI from
within vim itself
=> feature: Adding more commands

autoload/prettier.vim
This is another follow up fix for https://github.com/prettier/vim-prettier/issues/62, enables user to still have their buffer formatted event when switching to other files faster than the async result is returned.
cc @alanhamlett
=> Making sure we can still save the results of last prettier async run on

autoload/prettier.vim, doc/prettier.txt
Including plugin header information 
Fixes: https://github.com/prettier/vim-prettier/issues/67
=> Including extra information on the autoload header and doc header

package.json
=> Bumping prettier dep to 1.9.1

README.md, autoload/prettier.vim, doc/prettier.txt, plugin/prettier.vim
I made the default value `preserve` but let me know if you prefer another default!
From #88
=> Add --prose-wrap option

README.md, autoload/prettier.vim
=> Fixing lint

README.md
Support for vue files was added in https://github.com/prettier/prettier/pull/3563
=> Add vue file format to README

package.json
Bumping prettier dependencie to 1.10.2
=> Bumping prettier dependencie to 1.10.2

ftdetect/vue.vim, ftplugin/vue.vim
This PR adds support for detecting .vue files extensions
=> Adding vue file detect

README.md, doc/prettier.txt
Updating the docs for stating vue support
=> Updating docs with vue support reference

autoload/prettier.vim
=> Fix #108 spaces in executable path problem

README.md, autoload/prettier.vim, doc/prettier.txt, plugin/prettier.vim
* * *
**Summary**
- Negation flags are usually more confusing to understand specially when
the default is having it enabled.
**Test Plan**
Ensures that the quickfix controls are respected by `.vimrc` configuration overwrites
=> Updating the logic for controlling the quickfix flag

.travis.yml, ftdetect/css.vim, ftdetect/graphql.vim, ftdetect/javascript.vim, ftdetect/json.vim, ftdetect/less.vim, ftdetect/markdown.vim, ftdetect/scss.vim, ftdetect/typescript.vim, ftdetect/vue.vim
- Making sure that we group filedetect into its own groups
=> Fixing linting rules

ftdetect/lua.vim, ftdetect/php.vim, ftdetect/python.vim, ftdetect/swift.vim, ftplugin/lua.vim, ftplugin/php.vim, ftplugin/python.vim, ftplugin/swift.vim, package.json
This is a rebase of https://github.com/prettier/vim-prettier/pull/120/files
=> Rebasing vim-prettier plugin Pull Request 120 to 1.0 branch

ftdetect/html.vim, ftplugin/html.vim, package.json
* * * 
**Summary**
Upgraded the prettier version
Added support for html files
**Test Plan**
Tested using a plain html file
[...]
=> Added html support using the latest prettier 1.15 version

ftdetect/javascript.vim, ftdetect/typescript.vim
* * * 
**Summary**
Now I can't use prettier on `tsx` file and `jsx` file even when I put `typescript` and `javascript`. So thats' why I added some file extensions. I'm not sure if it's correct way, so please give a comment if you have any ideas or opinions.
Added `.tsx` to `typescript`
Added  `.jsx` to `javascript`
[...]
**Test Plan**
[...]
=> Added some file extensions

README.md
=> improve Requirement's message clearness

package.json, tests/__snapshots__/formatting.test.js.snap, tests/fixtures/foo.js, tests/formatting.test.js
This PR will be adding support writing integration tests using `vim-driver`
Todos:
cc @SamHowie
=> Integrating vim driver

README.md
* * * 
**Summary**
The current version of the readme returns a syntax error when attempting to downgrade. Added a '\\' to fix the syntax error.
**Test Plan**
No test plan. Just a simple fix to the README.md file about how to downgrade.
=> Fix readme to properly reflect how to downgrade

README.md
No need for pathogen, plug, vundle, etc anymore
=> Add instructions for installing with vim 8+

doc/prettier.txt
**Summary**
Adding the changes from #256 into the proper Vim doc document
=> Add buffer-level prettier exec command to doc

autoload/prettier/utils/buffer.vim
* * * 
**Summary**
[...]
**Test Plan**
[...]
=> fixes #244

package.json
addresses #268
* * * 
**Summary**
Tested to work so far on macvim without needing to make changes to my `.vimrc`. This fixes issue #268 where you would get the error:
```
Prettier: failed to parse buffer
```
It uses the solution found by @gadkadosh https://github.com/prettier/vim-prettier/issues/268#issuecomment-748026831. 
```
khuynh@kmac:plugged/vim-prettier …
```
=> bump @prettier/plugin-php dep

ftdetect/typescript.vim
fix #273 
Changed the filetype of tsx file to typescriptreact. It does not interfere with formatting.
=> #273 changed tsx filetype to typescriptreact

plugin/prettier.vim
Reopened https://github.com/prettier/vim-prettier/pull/275
Makes vim-prettier work with MDX out of the box
=> Autoformat MDX

plugin/prettier.vim
=> Remove Pipe

README.md
**Summary**
Took me a while to figure out how to get this properly installed with dein.  At one point the CLI Path stopped getting set (likely because I was changing directories and silently using the projects prettier cli).
Small change to add a sample Dein Config to the README
**Test Plan**
Review the README.md and ensure it is still rendering properly and clearly showing the dein config.
=> Add dein config to readme

README.md
**Summary**
Corrects minor typo in ReadMe
**Test Plan**
N/A
=> docs: Fixing typo in readme

README.md
**Summary**
- Install without making git status dirty
- Minimise node_modules size
**Test Plan**
1. rm -fr .vim/plugged/vim-prettier/
2. vim
3. :PlugInstall
4. vim index.js
5. i{"a":0x61}
6. trigger vim-prettier
7. {"a":0x61} becomes {a:0x61}
=> Improve install instruction

README.md
**Summary**
Readme clarification on how to get autoformat to work on save. It tripped me up (and [others](https://github.com/prettier/vim-prettier/issues/191)).
**Test Plan**
None
=> readme: example config: autoformat on save without pragma
