prettier/vim-prettier

- autoload/prettier.vim
Making sure we check the system exit code before overwriting the buffer. In case of error we can display an error message.
fixes: https://github.com/mitermayer/vim-prettier/issues/2
> bugfix: Making sure that when prettier fail to parse buffer we do not

- README.md
- autoload/prettier.vim
Add support for async formatting, make the default autosave behaviour use the async formating. 
implements https://github.com/mitermayer/vim-prettier/issues/4
> Adding support for async formating and making it default for autosave

- autoload/prettier.vim
Vim string comparisons are always false :(
fixing bug where prettier installation of the plugin was never
fixes: https://github.com/mitermayer/vim-prettier/issues/7
> bugfix: fixing bug where prettier installation of the plugin was never

- autoload/prettier.vim
- ftplugin/css.vim
- ftplugin/less.vim
- ftplugin/scss.vim
- ftplugin/typescript.vim
- package.json
- plugin/prettier.vim
- bumping plugin prettier version
- minor fix, removing dead code
- enabling partial  from visual selection
this fixes: https://github.com/mitermayer/vim-prettier/issues/14
> feature: enabling partial buffer conversion

- README.md
- doc/prettier.txt
This PR aligns the default settings for `prettier` based on the [current settings](https://github.com/prettier/prettier#options) specified in the `prettier` repo.
> Fix default settings

- README.md
- doc/prettier.txt
- ftplugin/graphql.vim
- ftplugin/json.vim
- package.json
- plugin/prettier.vim
This PR adds the `json` option as an option for the parser configuration (originally from #16 but extracted as a separate PR as a release with the `json` parser hasn't landed on `npm` yet.
TODO:
> Add JSON/GraphQL parser (prettier 1.5)

- ftdetect/css.vim
- ftdetect/graphql.vim
- ftdetect/javascript.vim
- ftdetect/json.vim
- ftdetect/less.vim
- ftdetect/scss.vim
- ftdetect/typescript.vim
We should provide some basic filetype detection but also keeping compatible with other plugins.
This for example would enable to correctly identify graphql, typescript, less, scss etc.. without having to rely on the filetype being implemented by other plugins.
Fixes: https://github.com/mitermayer/vim-prettier/issues/23
> feature/add-filetype-support - Adding filetype detection support when

- ftplugin/json.vim
- adding extra comma to the end properties cause creates invalid json
fixes https://github.com/mitermayer/vim-prettier/issues/26
> bugfix: json parser should not add extra comma to the end

- autoload/prettier.vim
Some other plugins also use quickfix for handling some internal functionality, we should therefore never clean or close the quickfix unless it was opened by vim-prettier itself.
- making sure quickfix list is not cleared unless it is already opened
with errors
fixes: https://github.com/prettier/vim-prettier/issues/39
> bugfix: should not clear quickfix unless opened by vim-prettier itself

- autoload/prettier.vim
This will make sure async command works for normal windows shells.
Fixes: https://github.com/prettier/vim-prettier/issues/44 and https://github.com/prettier/vim-prettier/issues/46
> Async command was not working for windows this patch will make sure it

- autoload/prettier.vim
This makes sure that after formatting and pressing <C-O> you get to stay in the same line instead of jumping to the beginning of the file.
fix: https://github.com/prettier/vim-prettier/issues/48
> Making sure that after formatting we preserve in the same line

- README.md
- autoload/prettier.vim
- doc/prettier.txt
- package.json
- plugin/prettier.vim
This PR adds full support for prettier 1.7 including the project based configuration.
This can only be merged once this https://github.com/prettier/prettier/pull/2733 is present on a new prettier release.
Will also bump `vim-prettier` to minor release since the new configuration `--config-precedence` is incompatible with older prettier CLI versions
fixes: https://github.com/prettier/vim-prettier/issues/51
> Issue/51 adding support for prettier 1.7

- README.md
- autoload/prettier.vim
- doc/prettier.txt
- plugin/prettier.vim
Allow user to set a the prettier CLI path via vim configuration.
fixes: https://github.com/prettier/vim-prettier/issues/56
> issue/56 - Allowing user path overwrite configuration

- autoload/prettier.vim
If user saved file and changed buffer too fast there was a chance that it could add the previous formatting to the next buffer when using vim 8 async job
Fixes: https://github.com/prettier/vim-prettier/issues/62
> bugfix: fixing race condition incorrect buffer formating

- ftplugin/css.vim
- ftplugin/graphql.vim
- ftplugin/javascript.vim
- ftplugin/json.vim
- ftplugin/less.vim
- ftplugin/scss.vim
- ftplugin/typescript.vim
bugfix: Fixing auto command params to use file extensions instead of magic <buffer> variable
> bugfix: Fixing auto command params to use extensions instead of magic

- autoload/prettier.vim
Adding support for Vim versions older than 8.0-0015 
> My vim doesn't have patch-8.0-0015, which is when support for options was added to ch_status. Could we remove {'part': 'out'} from this line?
cc @alanhamlett
> adding suppor for vim8 versions older than 8.0.0015 to use async job API

- autoload/prettier.vim
We need to include the full path of the edited file to `--stdin-filepath` in order for `prettier` to correctly identify configuration file that is nearest to the edited file.
fixes: https://github.com/prettier/vim-prettier/issues/71
> Fixing bug where config was not being correctly loaded based on file

- autoload/prettier.vim
File path could have invalid charactors for command line usage. `:h shellescape()`
> Add shellescape for file path

- autoload/prettier.vim
**Broken async formatting when we introduced file shell escaping**
For now we will revert back the PR (https://github.com/prettier/vim-prettier/pull/74) and then try addressing this again in subsequent PR's making sure we don't introduce new regressions.
fixes: https://github.com/prettier/vim-prettier/issues/76
> issues/76 - the shellescapping util function was breaking async

- README.md
- doc/prettier.txt
- ftdetect/markdown.vim
- ftplugin/css.vim
- ftplugin/graphql.vim
- ftplugin/json.vim
- ftplugin/less.vim
- ftplugin/markdown.vim
- ftplugin/scss.vim
- ftplugin/typescript.vim
- package.json
Adds support for prettier 1.8
* Run `prettier` on README :)
* Pass the parsers explicitly to the configuration
* Bump internal plugin dependency
* Add support for markdown formatting
* Update readme and docs
fixes: https://github.com/prettier/vim-prettier/issues/77
> Issue 77/adding support for prettier 1.8

- autoload/prettier.vim
- Latest prettier version introduced a regression when using
config-precedence
- https://github.com/prettier/prettier/issues/3432
fixes: https://github.com/prettier/vim-prettier/issues/84 and https://github.com/prettier/vim-prettier/issues/83
> issues-83-and-84 - Fixing prettier 1.9 regression

- autoload/prettier.vim
Will come up with a more generic fix inside `prettier` itself but in the meantime making sure we do not replace contents with empty buffer fix the issue of `ignored` files been overwritten.
fixes: https://github.com/prettier/vim-prettier/issues/92
This issue (https://github.com/prettier/prettier/issues/3590) will track the fix inside prettier itself
> bugfix - making sure we do not replace content with empty buffer

- autoload/prettier.vim
Using job control for async job when using neovim.
> Add async support for neovim

- README.md
I wanted to use this plugin but with the default Prettier options. I looked here https://prettier.io/docs/en/options.html and compared manually. I thought it might be helpful to have them directly in the readme.
> Add default option values from Prettier for configuration

- autoload/prettier.vim
- plugin/prettier.vim
- The new nvim async had some bugs reported, while we are still investigating fixes for it we will then disable it by default, users should be able to still use it by enabling the flag on their .vimrc in the meantime `g:prettier#nvim_unstable_async`
It's important for us to get the neovim integration working, but since there has been some bugs reported on it we need to make sure we mature it a bit more prior to removing the darkfeature flag, users that want to still use neovim async feature can enable it by adding the darkfeature flag  `g:prettier#nvim_unstable_async` to their `.vimrc`
fixes: 96
> Disabling nvim async by default under feature flag

- autoload/prettier.vim
This PR complements https://github.com/prettier/vim-prettier/pull/110 by making sure the async operations also work with spaced path directories
> Fixing empty spaces directory for async

- autoload/prettier.vim
- doc/prettier.txt
- plugin/prettier.vim
By default setqflist focuses the quicklist, which is annoying.
This restores the cursor position after calling setqflist.
> don't change focus to the quicklist

- README.md
**Summary**
As per the conversation under issue #102, this tweaks the syntax in the config overrides section of the project's README file.
> Amend syntax in documentation around config overrides

- autoload/prettier/job/async/neovim.vim
**Summary**
Use buffered mode for neovim job, which could avoid problem mentioned in #96
> use buffered mode for neovim job

- autoload/prettier.vim
**Summary**
This pull request fixes #135 where the command `PrettierAsync` causes Vim to crash due to segmentation fault.
The following is a summary of the involved fixes:
*Transportation fix:*
1. Change the jobs `in_io` back to the default of `pipe`
2. Read the selected buffer lines and write them to the jobs channel
3. Close the in channel to tell the job we have finished sending
*Performance fix:*
1. Use a simpler method to delete all lines in the buffer
2. Loop through and append all the lines we want to write to the buffer
**Test Plan**
*Error Reproduction Steps:*
1. Copy the `crash.js` file from @nerfologist reproduction example - https://raw.githubusercontent.com/nerfologist/vim-prettier-async-segv-bug/master/crash.js
2. Open `crash.js` in vim
3. Execute `PrettierAsync`
4. Notice …
> Fix PrettierAsync segmentation fault

- README.md
**Summary**
The example that shows how to enable `vim-prettier` for all files had a comment about only enabling it for supported files (looks like it was copy and pasted from the previous example).
**Test Plan**
Not needed
> Remove wrong comment on README.md comment example

- autoload/prettier.vim
**Summary**
This pull request fixes #140 where the PrettierAsync command causes the buffer contents to become garbled if the file is ignored by prettier.
It was found to be an issue with more recent versions of prettier that echo the stdin[1] of ignored files back to stdout[2].
1. https://github.com/prettier/prettier/blob/fb74dc54c337b92e2be6dfffe147ab42143e4e48/src/cli/util.js#L313
2. https://github.com/prettier/prettier/blob/fb74dc54c337b92e2be6dfffe147ab42143e4e48/src/cli/util.js#L126
Unfortunately, Vim channels do not like this very much. Vim writes NUL bytes to Prettier's stdin to indicate line endings. However, Prettier is echoing them back and then Vim is having trouble reading them back from what it thinks is a string, leading to undefined behaviour.
> A String in Vim cannot …
> Fix PrettierAsync ignored file contents mangling

- autoload/prettier.vim
Hi, **Summary**
Removed the hardcoded `--no-editorconfig` option. This enables editorsupport again.
**Test Plan**
Tested on nvim 0.3.0 and prettier 1.13.0 with JavaScript.
Closes #141
> Enable the default editorconfig support again

- .travis.yml
- ftdetect/yaml.vim
- ftplugin/yaml.vim
**Summary**
This PR adds support for YAML files.
Previously calling `:Prettier` on YAML files would fail with the dreaded "Prettier: failed to parse buffer."
**Test Plan**
Edit any YAML file with the plugin installed. Do it without and with this PR applied and note the difference.
Did this with:
`VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun  7 2018 11:02:45)
macOS version` and prettier 1.14.2.
> Add YAML support

- autoload/prettier/resolver/config.vim
Just for reference. Adds a small white space.
> space for --use-tabs

- autoload/prettier.vim
* * * 
**Summary**
Wrap the path used for `--stdin-filepath` in quotes. This allows prettier to work with files that have whitespace in their paths.
references #108
**Test Plan**
1. Edit a file in a location with whitespace in the path (e.g., `/Users/jason/Library/Mobile Documents/foo.md`).
2. Run `:Prettier`.
3. Verify that prettier runs without error.
> Handle file paths with whitespace

- ftplugin/html.vim
**Summary**
Markdown check used to check for exact string `'markdown'` which was not robust for mdx files or similar, meaning the mangling referenced in issue #166 still applied to mdx. Now it just checks to see if the word "markdown" is in it, which is more resilient to this issue. Not sure if this is the best solution.
> Make markdown check more resilient

- README.md
- doc/prettier.txt
- plugin/prettier.vim
If user have custom file type plugin that set "parser" option, calling
":Prettier" will return error "Prettier: failed to parse buffer".
This was caused by running prettier with CLI option "--parser X" with
"--config-precedence prefer_file" will cause prettier to ignore the
"parser" option.
> Set default "config_precendence" to "file-override"

- .gitignore
**Summary**
Ignore the generated help tags file if present in git repository. This helps keep `git status` clean when tracking plugins using git submodules.
**Test Plan**
Running `:helptags ALL` regenerates all help tags files. Confirm that `git status` doesn't show `doc/tags` as an untracked file.
> Ignore generated help tags file

- README.md
- autoload/prettier.vim
- autoload/prettier/resolver/config.vim
- doc/prettier.txt
- ftplugin/html.vim
- plugin/prettier.vim
This diff adds support for `require-pragma` option
***
- Removes naive implementation of `require-pragma` in favour of `prettier` cli implementation. There should be no change of behaviour besides some performances improvements as we no longer scan through the file in search of pragma tags
- This diff also enables user to autoformat based on `@prettier` tag as well as `@format` as opposed to just `@format`
> Adding support for require-pragma and depracting previous naive implemenation

- ftplugin/css.vim
- ftplugin/graphql.vim
- ftplugin/html.vim
- ftplugin/javascript.vim
- ftplugin/json.vim
- ftplugin/less.vim
- ftplugin/markdown.vim
- ftplugin/scss.vim
- ftplugin/typescript.vim
- ftplugin/vue.vim
- ftplugin/yaml.vim
Due to the fact that `plugin` will be loaded after `ftplugin`(http://vimdoc.sourceforge.net/htmldoc/filetype.html#ftplugin-overrule),
even we set `g:prettier#autoformat` in plugin/prettier.vim, it's treated as undefined in ftplugin/*.vim.
This happened when using `vim-pathogen`.
> Use `get()` to check `g:prettier#autoformat` safely in ftplugin

- README.md
- autoload/prettier.vim
- doc/prettier.txt
- plugin/prettier.vim
This PR will automatically toggle auto-formatting (i.e. format on save, `prettier#autoformat`) if a Prettier config file is found in the current directory or any parent directories.
`.vimrc` used for testing:
```viml
call plug#begin()
Plug 'prettier/vim-prettier', { 'do': 'yarn install' }
call plug#end()
let g:prettier#autoformat_config_present = 1
let g:prettier#config#config_precedence = 'prefer-file'
```
> Toggle the autoformat setting based on config file presence.

- README.md
- autoload/prettier.vim
- plugin/prettier.vim
**Summary**
The `prettier#autoformat_config_present` option is useful but it only worked with files with pragma. Now, you can use `autoformat_config_present` even with files without pragma using this `autoformat_require_pragma` option.
**Test Plan**
Not sure
> New option: prettier#autoformat_require_pragma

- autoload/prettier.vim
- ftplugin/css.vim
- ftplugin/graphql.vim
- ftplugin/html.vim
- ftplugin/javascript.vim
- ftplugin/json.vim
- ftplugin/less.vim
- ftplugin/lua.vim
- ftplugin/markdown.vim
- ftplugin/php.vim
- ftplugin/ruby.vim
- ftplugin/scss.vim
- ftplugin/typescript.vim
- ftplugin/vue.vim
- ftplugin/xml.vim
- ftplugin/yaml.vim
- plugin/prettier.vim
**Summary**
Fixes #233
**Test Plan**
Regression tests:
* If `g:prettier#autoformat == 1` and `g:prettier#autoformat_config_present == 0`, ensure that `prettier` runs on buffer save, regardless of whether or not a config file is present.
* If `g:prettier#autoformat_config_present == 1`, ensure that `prettier` runs on buffer save if and only if a config file is present.
Tests for new behavior:
* Test for both bugs originally reported in #233
> Force reevaluation of autoformat settings at buffer write time

- plugin/prettier.vim
**Summary**
I was wondering why `g:prettier#autoformat_config_present = 1` wasn't working correctly; this is it.
> Fix string concatenation typo

- ftplugin/yaml.vim
**Summary**
Closes #245
The `autocmd` for `yaml` files miss the ".yml" extension
> Add missing ".yml" in autocmd

- autoload/prettier/job/async/neovim.vim
**Summary**
This fixes #215 by implementing the fix I've suggested in [my comment][0].
After [the suggestion to open a PR][1], here we are :)
[0]: https://github.com/prettier/vim-prettier/issues/215#issuecomment-629681399
[1]: https://github.com/prettier/vim-prettier/issues/215#issuecomment-648657236
**Test Plan**
Tested locally with nvim and fix has been confirmed by others in #215 to work.
> Fix error when quitting Neovim with :wq

- ftplugin/ruby.vim
* * * 
**Summary**
This adds `.rb` as an extension in `ftplugin/ruby.vim`, fixing a problem where ruby
files with a `.rb` extension were not being autoformatted.
**Test Plan**
I tested this locally by confirming that it now autoformats `.rb` files.
> Autoformat .rb files

- README.md
- autoload/prettier/resolver/executable.vim
**Summary**
Add the ability to set a buffer-level `b:prettier_exec_cmd` for different prettier commands between buffers. This allows the user, for instance, to use `prettier-stylelint` for CSS files if desired.
**Test Plan**
Not sure exactly how to test this, looking for advice.
---
Closes #255
> Add support for buffer-level prettier_exec_cmd, for prettier-stylelint for instance

- plugin/prettier.vim
**Summary**
Currently `vim-prettier` provides a set of overriding configs (like `#config#tab_width`, `#config#trailing_comma`,...) but there're some not respecting the [Prettier CLI's default options](https://prettier.io/docs/en/options.html), e.g.:
* `#config#trailing_comma` is `none` while it's `es5` by default.
* `#config#arrow_parens` is `avoid` while it's `always` by default.
This can lead to confusing situations, for instance: auto-saving produces strange diffs comparing to CLI running.
This PR aims to update those configs to respect official document, as well as provide references to it.
**Test Plan**
N/A
> Uses default cli configs

- ftplugin/css.vim
- ftplugin/graphql.vim
- ftplugin/html.vim
- ftplugin/javascript.vim
- ftplugin/json.vim
- ftplugin/less.vim
- ftplugin/lua.vim
- ftplugin/markdown.vim
- ftplugin/php.vim
- ftplugin/ruby.vim
- ftplugin/scss.vim
- ftplugin/typescript.vim
- ftplugin/vue.vim
- ftplugin/xml.vim
- ftplugin/yaml.vim
- plugin/prettier.vim
**Summary**
The `BufWritePre autocmds` are reset each time a file type plugin is run, which means if you open a file of one type, it will auto format correctly, but if you then open a file of a different type, the original file will no longer auto format.
See further explanation here: https://github.com/prettier/vim-prettier/issues/185#issuecomment-750987266
This PR removes the `augroup` from each of the ftplugin files and adds some missing file extensions to the `augroup` in `plugin/prettier.vim`.
**Test Plan**
[...]
> Stop blowing away the BufWritePre augroup in ftplugins

- autoload/prettier/resolver/executable.vim
**Summary**
This fixes an issue on nvim (v0.5.0, likely others) in which a local `prettier` installation is not found by `s:ResolveExecutable`, and it returns a `-1` for  `executable(_)` to choke on with a `String required` error.
The proposed change returns a sane default.
> Return cwd as default from s:ResolveExecutable

- README.md
- doc/prettier.txt
**Summary**
Fix incorrect reference to `:PartialFragment` in the readme and fix formatting on bold text
**Test Plan**
[...]
> fix incorrect reference to PrettierFragment in readme

- package.json
- yarn.lock
* * * 
**Summary**
Updated broken build dependency (prettier-php). It seems like the version of prettier and prettier-php were incompatible, which prevents a `yarn install`
This only matters when you're running vim-prettier without a global or local prettier binary available. So probably a lot of people won't experience it.
**Test Plan**
* Reinstall my fork from nvim and vim8
* Run `:Prettier` outside of an npm/yarn project, and without a globally installed prettier binary. Verify that it's working.
> fix for #287: update dependency (prettier-php) to fix build

- autoload/prettier/utils/buffer.vim
**Summary**
Fix marks buffer marks being lost after Prettier runs.
Fixes this issue #251 
**Test Plan**
- add a mark with `ma`, move around, jump to it with `'a`
- "uglify" a line in your code, run `:Prettier` to fix it
- now do `'a`, vim should jump the cursor to the marked position with `ma`. The line might not correspond exactly with the previous line due to lines changed by Prettier, but it should be close.
> enh: save buffer marks between runs

- package.json
- yarn.lock
**Summary**
Update prettier to its latest version. I found a problem with a prettier plugin not working when the version installed in the vim-prettier directory was used (`:Prettier` was not working on the files formatted by that plugin, but it was for javascript files) and upgrading fixed it.
**Test Plan**
I manually tested locally, but only in vim8.
> Update prettier to latest version
